title: schn00x
description: testing things
avatar: https://github.com/schn00x.png
analytics-id: G-6K8Q65ZCY3

links:
  - title: GitHub
    url: https://github.com/schn00x
    icon: "⚡"
  - title: Vinted
    url: https://www.vinted.at/member/3123811166-moritzs900
    icon: "🧦"
  - title: READO
    url: https://reado.app/profile/schn00x
    icon: "📚"